#!/bin/bash -x
# Add -x to above line for more verbose output
# Clean out the files installed by installit

# see installit for more relevant notes

# Bump this per push

version="0.04"

# Append your email addr here and append your name to the 
# copyright list with commas. 

# pete@soper.us

# MIT License
#
# Copyright 2022 Peter James Soper
#
# Permission is hereby granted, free of charge, to any person 
# obtaining a copy of this software and associated 
# documentation files (the "Software"), to deal in the
# Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, 
# distribute, sublicense, and/or sell copies of the
# Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall
# be included in all copies or substantial portions of the 
# Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY 
# KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE 
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
# PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Have to manually keep this default sync'd with installit

targetdir=~

# Don't modify lines below this one

true=1
false=0


completely=$false

usage() {
  echo $1
  echo "usage: cleanit [-target] [-completely]"
  exit 1
}

while [ $# -gt 0 ] ; do
  if [ $1 = "-version" ] ; then
    echo "version: $version"
    exit 0
  else
    usage "unknown option: $1"
  fi
done

if [ ! $USER = "root" ] ; then
  SUDO=sudo
fi

rm -rf $targetdir/esp-idf
rm -rf $targetdir/que_aardvark
rm -rf $targetdir/que_ant

